// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Nodefs = require("node:fs");
let Nodeos = require("node:os");
let Nodeurl = require("node:url");
let Nodehttp = require("node:http");
let Nodepath = require("node:path");
let Stdlib_JSON = require("@rescript/runtime/lib/js/Stdlib_JSON.js");
let Nodecrypto = require("node:crypto");
let Stdlib_Array = require("@rescript/runtime/lib/js/Stdlib_Array.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Stdlib_Promise = require("@rescript/runtime/lib/js/Stdlib_Promise.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");

let baseUrl = `http://localhost:` + (8888).toString();

let remoteUser = "alvis";

let remoteActor = `http://localhost:` + (9999).toString() + `/users/` + remoteUser;

let noteId = `http://localhost:` + (9999).toString() + `/users/` + remoteUser + `/statuses/reply/1`;

let samplesDir = Nodepath.join(__dirname, "samples");

async function httpGet(port, path) {
  let res = await fetch(`http://localhost:` + port.toString() + path, {
    method: "GET"
  });
  let body = await res.text();
  return {
    status: res.status,
    body: body
  };
}

async function httpPost(port, path, body, headers) {
  let res = await fetch(`http://localhost:` + port.toString() + path, {
    method: "POST",
    headers: headers,
    body: body
  });
  let respBody = await res.text();
  return {
    status: res.status,
    body: respBody
  };
}

function genRsaKeyPair() {
  return Nodecrypto.generateKeyPairSync("rsa", {
    modulusLength: 2048,
    publicKeyEncoding: {
      type: "spki",
      format: "pem"
    },
    privateKeyEncoding: {
      type: "pkcs8",
      format: "pem"
    }
  });
}

function sha256b64(str) {
  return Nodecrypto.createHash("sha256").update(str).digest("base64");
}

function signedHeaders(body, reqPath, privateKey) {
  let d = new Date().toUTCString();
  let digest = "SHA-256=" + sha256b64(body);
  let toSign = `(request-target): post ` + reqPath + `\n` + (`host: localhost:` + (8888).toString() + `\n`) + (`date: ` + d + `\n`) + (`digest: ` + digest);
  let sig = Nodecrypto.sign("sha256", Buffer.from(toSign), privateKey).toString("base64");
  return Object.fromEntries([
    [
      "content-type",
      "application/activity+json"
    ],
    [
      "host",
      `localhost:` + (8888).toString()
    ],
    [
      "date",
      d
    ],
    [
      "digest",
      digest
    ],
    [
      "signature",
      `keyId="` + remoteActor + `#main-key",algorithm="rsa-sha256",` + (`headers="(request-target) host date digest",signature="` + sig + `"`)
    ]
  ]);
}

function sample(name) {
  return Nodefs.readFileSync(Nodepath.join(samplesDir, name), "utf8");
}

function collectBody(req) {
  req.setEncoding("utf8");
  return new Promise((resolve, param) => {
    let chunks = [];
    req.on("data", c => {
      chunks.push(c);
    });
    req.on("end", () => resolve(chunks.join("")));
  });
}

function collectionContains(collection, id) {
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_Option.flatMap(collection, Stdlib_JSON.Decode.object), d => d["orderedItems"]), Stdlib_JSON.Decode.array), []).some(item => {
    let s = Stdlib_JSON.Decode.string(item);
    if (s !== undefined) {
      return s === id;
    } else {
      return Stdlib_Option.getOr(Stdlib_Option.map(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(item), d => d["id"]), Stdlib_JSON.Decode.string), s => s === id), false);
    }
  });
}

function jsonStringify(json) {
  return Stdlib_Option.getOr(Stdlib_Option.map(json, j => JSON.stringify(j, undefined, 4)), "null");
}

async function runTest(name, fn) {
  let results = [];
  let assert_that = (cond, msg) => {
    results.push([
      cond,
      msg
    ]);
  };
  await fn(assert_that);
  return {
    name: name,
    checkings: results.length,
    failures: Stdlib_Array.filterMap(results, param => {
      if (param[0]) {
        return;
      } else {
        return name + `: ` + param[1];
      }
    })
  };
}

function encodeBase64(s) {
  return Buffer.from(s).toString("base64");
}

function decodeBase64(s) {
  return Buffer.from(s, "base64").toString();
}

function respond(res, code, headers, body) {
  res.writeHead(code, headers);
  res.end(body);
}

function sendJson(res, code, body) {
  respond(res, code, Object.fromEntries([[
      "Content-Type",
      "application/json"
    ]]), body);
}

function startGitHubShim(dataDir, port) {
  let server = Nodehttp.createServer(async (req, res) => {
    let reqPath = Stdlib_Option.getOr(Primitive_option.fromNullable(req.url), "/");
    let method_ = Stdlib_Option.getOr(Primitive_option.fromNullable(req.method), "GET");
    let filePath = Nodepath.join(dataDir, reqPath);
    switch (method_) {
      case "DELETE" :
        if (Nodefs.existsSync(filePath)) {
          Nodefs.rmSync(filePath, {"recursive": true});
          return sendJson(res, 200, "{}");
        } else {
          return sendJson(res, 404, "{\"message\":\"Not Found\"}");
        }
      case "GET" :
        if (!Nodefs.existsSync(filePath)) {
          return sendJson(res, 404, "{\"message\":\"Not Found\"}");
        }
        let content = Nodefs.readFileSync(filePath, "utf8");
        return sendJson(res, 200, `{"content":"` + Buffer.from(content).toString("base64") + `", "sha":"shim"}`);
      case "PUT" :
        let body = await collectBody(req);
        let s = Stdlib_Option.getOrThrow(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(JSON.parse(body)), d => d["content"]), Stdlib_JSON.Decode.string), undefined);
        let content$1 = Buffer.from(s, "base64").toString();
        Nodefs.mkdirSync(Nodepath.dirname(filePath), {"recursive": true});
        Nodefs.writeFileSync(filePath, content$1, "utf8");
        return sendJson(res, 200, "{}");
      default:
        return sendJson(res, 405, "{\"message\":\"Method Not Allowed\"}");
    }
  });
  return new Promise((resolve, param) => {
    server.listen(port, () => resolve());
  });
}

function startDevServer(handler, port) {
  let server = Nodehttp.createServer(async (req, res) => {
    let body = await collectBody(req);
    let rawUrl = Stdlib_Option.getOrThrow(Primitive_option.fromNullable(req.url), undefined);
    let url = new Nodeurl.URL(rawUrl, "http://localhost");
    let httpMethod = Stdlib_Option.getOrThrow(Primitive_option.fromNullable(req.method), undefined);
    let event_path = url.pathname;
    let event_headers = req.headers;
    let event_body = body === "" ? undefined : body;
    let event = {
      path: event_path,
      httpMethod: httpMethod,
      headers: event_headers,
      body: event_body
    };
    let response = httpMethod === "HEAD" ? ({
        statusCode: 200
      }) : await handler(event, undefined);
    return respond(res, response.statusCode, Stdlib_Option.getOr(response.headers, {}), Stdlib_Option.getOr(response.body, ""));
  });
  return new Promise((resolve, param) => {
    server.listen(port, () => resolve());
  });
}

async function startRemoteActor(publicKey) {
  let actorJson = JSON.stringify({
    "@context": "https://www.w3.org/ns/activitystreams",
    id: remoteActor,
    type: "Person",
    inbox: `http://localhost:` + (9999).toString() + `/inbox`,
    publicKey: {
      id: remoteActor + `#main-key`,
      owner: remoteActor,
      publicKeyPem: publicKey
    }
  });
  let acceptWaiter = {
    contents: undefined
  };
  let server = Nodehttp.createServer(async (req, res) => {
    let body = await collectBody(req);
    let method = Stdlib_Option.getOr(Primitive_option.fromNullable(req.method), "GET");
    let url = Stdlib_Option.getOr(Primitive_option.fromNullable(req.url), "/");
    switch (method) {
      case "GET" :
        if (url === `/users/` + remoteUser) {
          return respond(res, 200, Object.fromEntries([[
              "Content-Type",
              "application/activity+json"
            ]]), actorJson);
        }
        break;
      case "POST" :
        if (url === "/inbox") {
          Stdlib_Option.forEach(acceptWaiter.contents, resolve => resolve(body));
          acceptWaiter.contents = undefined;
          return respond(res, 200, {}, "");
        }
        break;
    }
    return respond(res, 404, {}, "");
  });
  await new Promise((resolve, param) => {
    server.listen(9999, () => resolve());
  });
  return () => new Promise((resolve, param) => {
    acceptWaiter.contents = resolve;
  });
}

async function runTests(remotePrivateKey, tmpDataDir, waitForAccept) {
  let readData = relPath => {
    let full = Nodepath.join(tmpDataDir, relPath);
    if (Nodefs.existsSync(full)) {
      return JSON.parse(Nodefs.readFileSync(full, "utf8"));
    }
  };
  let inboxTest = (name, sampleFile, dataPath, id, addMode, expectAcceptOpt) => {
    let expectAccept = expectAcceptOpt !== undefined ? expectAcceptOpt : false;
    return runTest(name, async assert_that => {
      let pendingAccept = expectAccept ? waitForAccept() : undefined;
      assert_that(collectionContains(readData(dataPath), id) !== addMode, "precondition failed");
      let body = sample(sampleFile);
      let res = await httpPost(8888, "/inbox", body, signedHeaders(body, "/inbox", remotePrivateKey));
      assert_that(res.status === 200, `status=` + res.status.toString());
      if (pendingAccept !== undefined) {
        let accepted = await pendingAccept;
        let tmp;
        try {
          tmp = Stdlib_Option.map(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(JSON.parse(accepted)), d => d["type"]), Stdlib_JSON.Decode.string), t => t === "Accept");
        } catch (exn) {
          tmp = undefined;
        }
        let isAccept = Stdlib_Option.getOr(tmp, false);
        assert_that(isAccept, `Accept not delivered; captured: ` + accepted);
      }
      let data = readData(dataPath);
      return assert_that(collectionContains(data, id) === addMode, `collection state wrong; got: ` + jsonStringify(data));
    });
  };
  return [
    await runTest("GET /actor", async assert_that => {
      let res = await httpGet(8888, "/actor");
      let typeField;
      try {
        typeField = Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(JSON.parse(res.body)), d => d["type"]), Stdlib_JSON.Decode.string);
      } catch (exn) {
        typeField = undefined;
      }
      return assert_that(res.status === 200 && typeField === "Person", `status=` + res.status.toString() + ` type=` + Stdlib_Option.getOr(typeField, "none"));
    }),
    await inboxTest("Follow", "follow.json", "followers", remoteActor, true, true),
    await inboxTest("Undo Follow", "unfollow.json", "followers", remoteActor, false, undefined),
    await inboxTest("Like", "like.json", "likes/test-note-1", remoteActor, true, undefined),
    await inboxTest("Undo Like", "unlike.json", "likes/test-note-1", remoteActor, false, undefined),
    await inboxTest("Announce", "announce.json", "announces/test-note-1", remoteActor, true, undefined),
    await inboxTest("Undo Announce", "unannounce.json", "announces/test-note-1", remoteActor, false, undefined),
    await inboxTest("Create reply", "reply.json", "replies/test-note-1", noteId, true, undefined),
    await inboxTest("Delete", "delete.json", "replies/test-note-1", noteId, false, undefined)
  ];
}

async function main() {
  let localKeys = genRsaKeyPair();
  let remoteKeys = genRsaKeyPair();
  let tmpDataDir = Nodefs.mkdtempSync(Nodepath.join(Nodeos.tmpdir(), "lesspub-test-"));
  let fakeActorJsonPath = Nodepath.join(tmpDataDir, "actor.json");
  Nodefs.writeFileSync(fakeActorJsonPath, JSON.stringify({
    "@context": [
      "https://www.w3.org/ns/activitystreams",
      "https://w3id.org/security/v1"
    ],
    id: baseUrl + `/actor`,
    type: "Person",
    inbox: baseUrl + `/inbox`,
    publicKey: {
      id: baseUrl + `/actor#main-key`,
      owner: baseUrl + `/actor`,
      publicKeyPem: localKeys.publicKey
    }
  }), "utf8");
  let env = process.env;
  env["AP_BASE_URL"] = baseUrl;
  env["AP_PRIVATE_KEY"] = localKeys.privateKey.replace(/\n/g, "\\n");
  env["AP_GH_TOKEN"] = "test";
  env["AP_GH_BASE_URL"] = `http://localhost:` + (3001).toString();
  env["AP_EXTRA_INBOXES"] = "";
  env["AP_GH_DATA_DIR"] = tmpDataDir;
  env["AP_ACTOR_JSON_PATH"] = fakeActorJsonPath;
  let handler = require("../src/Index.js").handler;
  let waitForAccept = await startRemoteActor(remoteKeys.publicKey);
  await startGitHubShim(tmpDataDir, 3001);
  await startDevServer(handler, 8888);
  let cleanup = () => {
    try {
      Nodefs.rmSync(tmpDataDir, {"recursive": true});
      return;
    } catch (exn) {
      return;
    }
  };
  let results;
  try {
    results = await runTests(remoteKeys.privateKey, tmpDataDir, waitForAccept);
  } catch (e) {
    cleanup();
    throw e;
  }
  cleanup();
  let allCheckings = Stdlib_Array.reduce(results, 0, (s, r) => s + r.checkings | 0);
  let allFailures = Stdlib_Array.reduce(results, [], (acc, r) => acc.concat(r.failures));
  let passing = results.filter(r => r.failures.length === 0).length;
  let failing = results.length - passing | 0;
  console.log(`[Info] ` + results.length.toString() + ` tests, ` + passing.toString() + ` passing, ` + failing.toString() + ` failing, ` + allCheckings.toString() + ` checkings.`);
  allFailures.forEach(prim => {
    console.log(prim);
  });
  process.exit(failing > 0 ? 1 : 0);
}

Stdlib_Promise.$$catch(main(), e => {
  console.error(e);
  process.exit(1);
  return Promise.resolve();
});

let devPort = 8888;

let ghShimPort = 3001;

let remotePort = 9999;

exports.devPort = devPort;
exports.ghShimPort = ghShimPort;
exports.remotePort = remotePort;
exports.baseUrl = baseUrl;
exports.remoteUser = remoteUser;
exports.remoteActor = remoteActor;
exports.noteId = noteId;
exports.samplesDir = samplesDir;
exports.httpGet = httpGet;
exports.httpPost = httpPost;
exports.genRsaKeyPair = genRsaKeyPair;
exports.sha256b64 = sha256b64;
exports.signedHeaders = signedHeaders;
exports.sample = sample;
exports.collectBody = collectBody;
exports.collectionContains = collectionContains;
exports.jsonStringify = jsonStringify;
exports.runTest = runTest;
exports.encodeBase64 = encodeBase64;
exports.decodeBase64 = decodeBase64;
exports.respond = respond;
exports.sendJson = sendJson;
exports.startGitHubShim = startGitHubShim;
exports.startDevServer = startDevServer;
exports.startRemoteActor = startRemoteActor;
exports.runTests = runTests;
exports.main = main;
/* baseUrl Not a pure module */
