// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var baseURL = Belt_Option.getExn(Js_dict.get(process.env, "AP_BASE_URL"));

var privateKey = Belt_Option.getExn(Js_dict.get(process.env, "AP_PRIVATE_KEY"));

var ghToken = Belt_Option.getExn(Js_dict.get(process.env, "AP_GH_TOKEN"));

var ghBaseURL = Belt_Option.getExn(Js_dict.get(process.env, "AP_GH_BASE_URL"));

var actor = baseURL + "/actor";

var keyId = actor + "#main-key";

var functionPath = "/.netlify/functions/lesspub";

exports.baseURL = baseURL;
exports.privateKey = privateKey;
exports.ghToken = ghToken;
exports.ghBaseURL = ghBaseURL;
exports.actor = actor;
exports.keyId = keyId;
exports.functionPath = functionPath;
/* baseURL Not a pure module */
