[[redirects]]
from = "/actor"
to = "/.netlify/functions/lesspub/actor"
status = 200

[[redirects]]
from = "/inbox"
to = "/.netlify/functions/lesspub/inbox"
status = 200

[[headers]]
for = "/.well-known/webfinger"
[headers.values]
Content-Type = "application/jrd+json"

[[headers]]
for = "/actor.jsonld"
[headers.values]
Content-Type = "application/activity+json"

[[headers]]
for = "/followers"
[headers.values]
Content-Type = "application/activity+json"

[[headers]]
for = "/outbox"
[headers.values]
Content-Type = "application/activity+json"

[[headers]]
for = "/note/*"
[headers.values]
Content-Type = "application/activity+json"

[[headers]]
for = "/create/*"
[headers.values]
Content-Type = "application/activity+json"

[[headers]]
for = "/likes/*"
[headers.values]
Content-Type = "application/activity+json"

[[headers]]
for = "/replies/*"
[headers.values]
Content-Type = "application/activity+json"
