// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Pervasives = require("@rescript/runtime/lib/js/Pervasives.js");
let Stdlib_JSON = require("@rescript/runtime/lib/js/Stdlib_JSON.js");
let Stdlib_Type = require("@rescript/runtime/lib/js/Stdlib_Type.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Stdlib_Result = require("@rescript/runtime/lib/js/Stdlib_Result.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");

function classify(t) {
  let string = Stdlib_Type.Classify.classify(t);
  if (typeof string !== "object") {
    return Pervasives.failwith("Unreachable code");
  }
  switch (string.TAG) {
    case "String" :
      return {
        TAG: "String",
        _0: string._0
      };
    case "Object" :
      return {
        TAG: "Wrap",
        _0: string._0
      };
    default:
      return Pervasives.failwith("Unreachable code");
  }
}

let StringOption = {
  classify: classify
};

function getId(ooi) {
  let id = classify(ooi);
  if (id.TAG === "String") {
    return id._0;
  } else {
    return id._0.id;
  }
}

function toJSON(o) {
  let match = o["@context"];
  if (match !== undefined) {
    
  } else {
    o["@context"] = "https://www.w3.org/ns/activitystreams";
  }
  return o;
}

function isJSONString(json) {
  return Stdlib_Option.isSome(Stdlib_JSON.Decode.string(json));
}

function validateJSON(json) {
  let dict = Stdlib_JSON.Decode.object(json);
  if (dict === undefined) {
    return false;
  }
  let id = Stdlib_Option.map(dict["id"], isJSONString);
  let type_ = Stdlib_Option.map(dict["type"], isJSONString);
  let obj = Stdlib_Option.map(dict["object"], x => {
    if (Stdlib_Option.isSome(Stdlib_JSON.Decode.string(x))) {
      return true;
    } else {
      return validateJSON(x);
    }
  });
  let orderedItems = Stdlib_Option.map(Stdlib_Option.flatMap(dict["orderedItems"], Stdlib_JSON.Decode.array), items => items.every(x => {
    if (Stdlib_Option.isSome(Stdlib_JSON.Decode.string(x))) {
      return true;
    } else {
      return validateJSON(x);
    }
  }));
  if (id === undefined) {
    return false;
  }
  if (!id) {
    return false;
  }
  if (type_ === undefined) {
    return false;
  }
  if (!type_) {
    return false;
  }
  if (obj !== undefined && !obj) {
    return false;
  }
  if (orderedItems !== undefined) {
    return orderedItems;
  } else {
    return true;
  }
}

function fromString(s) {
  let tmp;
  try {
    tmp = {
      TAG: "Ok",
      _0: JSON.parse(s)
    };
  } catch (exn) {
    tmp = {
      TAG: "Error",
      _0: "Error parsing JSON string"
    };
  }
  return Stdlib_Result.flatMap(tmp, x => {
    if (validateJSON(x)) {
      return {
        TAG: "Ok",
        _0: x
      };
    } else {
      return {
        TAG: "Error",
        _0: "JSON is not valid"
      };
    }
  });
}

function resultToOption(r) {
  return Stdlib_Result.mapOr(r, undefined, x => Primitive_option.some(x));
}

exports.StringOption = StringOption;
exports.getId = getId;
exports.toJSON = toJSON;
exports.isJSONString = isJSONString;
exports.validateJSON = validateJSON;
exports.fromString = fromString;
exports.resultToOption = resultToOption;
/* No side effect */
