// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Nodefs = require("node:fs");
let Nodepath = require("node:path");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");

let env = process.env;

let baseURL = Stdlib_Option.getOrThrow(env["AP_BASE_URL"], undefined);

let privateKey = Stdlib_Option.getOrThrow(env["AP_PRIVATE_KEY"], undefined).replace(/\\n/g, "\n");

let ghToken = Stdlib_Option.getOrThrow(env["AP_GH_TOKEN"], undefined);

let ghBaseURL = Stdlib_Option.getOrThrow(env["AP_GH_BASE_URL"], undefined);

let extraInboxes = Stdlib_Option.getOr(Stdlib_Option.map(env["AP_EXTRA_INBOXES"], s => s.split(",")), []);

let actor = baseURL + "/actor";

let keyId = actor + "#main-key";

let actorJSON = JSON.parse(Nodefs.readFileSync(Stdlib_Option.getOr(env["AP_ACTOR_JSON_PATH"], Nodepath.join(__dirname, "../../../../actor.json")), "utf8"));

exports.env = env;
exports.baseURL = baseURL;
exports.privateKey = privateKey;
exports.ghToken = ghToken;
exports.ghBaseURL = ghBaseURL;
exports.extraInboxes = extraInboxes;
exports.actor = actor;
exports.keyId = keyId;
exports.actorJSON = actorJSON;
/* env Not a pure module */
