// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Config = require("./Config.js");
let APObject = require("./APObject.js");
let Security = require("./Security.js");
let Nodeurl = require("node:url");

function post(inbox, activity) {
  let match = new Nodeurl.URL(inbox);
  let host = match.host;
  let body = JSON.stringify(APObject.toJSON(activity));
  let date = new Date().toUTCString();
  let digest = "SHA-256=" + Security.Hash.get(body);
  let to_be_signed = `(request-target): post ` + match.pathname + `\nhost: ` + host + `\ndate: ` + date + `\ndigest: ` + digest;
  let signature = Security.sign(to_be_signed);
  let fetch_options = {
    method: "POST",
    body: body,
    headers: {
      "content-type": "application/activity+json",
      host: host,
      date: date,
      digest: digest,
      signature: `keyId="` + Config.keyId + `",algorithm="rsa-sha256",headers="(request-target) host date digest",signature="` + signature + `"`
    }
  };
  console.log("I will send:", fetch_options);
  return fetch(inbox, fetch_options);
}

exports.post = post;
/* Config Not a pure module */
