// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Config = require("./Config.js");
let APObject = require("./APObject.js");
let Stdlib_JSON = require("@rescript/runtime/lib/js/Stdlib_JSON.js");
let Stdlib_Array = require("@rescript/runtime/lib/js/Stdlib_Array.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Primitive_object = require("@rescript/runtime/lib/js/Primitive_object.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

let headers = {
  accept: "application/activity+json"
};

async function fetchKey(keyId) {
  let res = await fetch(keyId, {
    headers: headers
  });
  try {
    return Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_Option.flatMap((await res.json())["publicKey"], Stdlib_JSON.Decode.object), x => x["publicKeyPem"]), Stdlib_JSON.Decode.string);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return;
    }
    throw exn;
  }
}

async function fetchInbox(actor) {
  let res = await fetch(actor, {
    headers: headers
  });
  try {
    return Stdlib_Option.flatMap((await res.json())["inbox"], Stdlib_JSON.Decode.string);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return;
    }
    throw exn;
  }
}

function atob(s) {
  return Buffer.from(s).toString("base64");
}

function btoa(s) {
  return Buffer.from(s, "base64").toString();
}

let headers$1 = {
  accept: "application/vnd.github+json",
  authorization: "Bearer " + Config.ghToken,
  "x-gitHub-api-version": "2022-11-28"
};

async function put(content, path, sha) {
  return (await fetch(Config.ghBaseURL + path, {
    method: "PUT",
    headers: headers$1,
    body: JSON.stringify({
      message: "Update ActivityPub file",
      committer: {
        name: "LessPub Bot",
        email: "no-email@example.com"
      },
      content: Buffer.from(content).toString("base64"),
      sha: sha
    })
  })).ok;
}

async function $$delete(path, sha) {
  return (await fetch(Config.ghBaseURL + path, {
    method: "DELETE",
    headers: headers$1,
    body: JSON.stringify({
      message: "Delete ActivityPub file",
      committer: {
        name: "LessPub Bot",
        email: "no-email@example.com"
      },
      sha: sha
    })
  })).ok;
}

async function get(path) {
  let res = await fetch(Config.ghBaseURL + path, {
    headers: headers$1
  });
  if (!res.ok) {
    return [
      undefined,
      undefined
    ];
  }
  let dict = await res.json();
  let content = Stdlib_Option.map(Stdlib_Option.flatMap(dict["content"], Stdlib_JSON.Decode.string), btoa);
  let sha = Stdlib_Option.flatMap(dict["sha"], Stdlib_JSON.Decode.string);
  return [
    content,
    sha
  ];
}

async function insertToFile(ooi, path) {
  let match = await get(path);
  let collection = Stdlib_Option.getOr(Stdlib_Option.flatMap(match[0], x => APObject.resultToOption(APObject.fromString(x))), {
    id: Config.baseURL + path,
    type: "OrderedCollection",
    totalItems: 0,
    orderedItems: []
  });
  let totalItems = Stdlib_Option.getOr(collection.totalItems, 0);
  let orderedItems = Stdlib_Option.getOr(collection.orderedItems, []);
  if (orderedItems.some(x => Primitive_object.equal(x, ooi))) {
    return true;
  } else {
    collection.totalItems = 1 + totalItems | 0;
    collection.orderedItems = [ooi].concat(orderedItems);
    return await put(JSON.stringify(APObject.toJSON(collection), undefined, 4), path, match[1]);
  }
}

async function removeFromFile(ooi, path) {
  let match = await get(path);
  let sha = match[1];
  let collection = Stdlib_Option.flatMap(match[0], x => APObject.resultToOption(APObject.fromString(x)));
  if (collection === undefined) {
    return true;
  }
  let collection$1 = Primitive_option.valFromOption(collection);
  let totalItems = Stdlib_Option.getOr(collection$1.totalItems, 0);
  let orderedItems = Stdlib_Option.getOr(collection$1.orderedItems, []);
  let id = APObject.getId(ooi);
  console.log(totalItems, sha, id);
  let match$1 = Stdlib_Array.findIndexOpt(orderedItems, x => id === APObject.getId(x));
  if (match$1 !== undefined) {
    if (totalItems !== 1) {
      collection$1.totalItems = totalItems - 1 | 0;
      collection$1.orderedItems = orderedItems.filter((param, j) => j !== match$1);
      return await put(JSON.stringify(APObject.toJSON(collection$1), undefined, 4), path, sha);
    } else {
      return await $$delete(path, Stdlib_Option.getOrThrow(sha, undefined));
    }
  } else {
    return true;
  }
}

let GitHub = {
  atob: atob,
  btoa: btoa,
  headers: headers$1,
  put: put,
  $$delete: $$delete,
  get: get,
  insertToFile: insertToFile,
  removeFromFile: removeFromFile
};

exports.headers = headers;
exports.fetchKey = fetchKey;
exports.fetchInbox = fetchInbox;
exports.GitHub = GitHub;
/* Config Not a pure module */
