// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fetch = require("./Fetch.js");
var Config = require("./Config.js");
var Egress = require("./Egress.js");
var Nodeurl = require("node:url");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Js_promise2 = require("rescript/lib/js/js_promise2.js");
var Nodecrypto = require("node:crypto");

async function main(param) {
  var actors = ["https://dvd.chat/users/9gt1gfwbnibzwcur"];
  var inboxes = await Promise.all(actors.map(Fetch.fetchInbox));
  var pairs = Belt_Array.keepMap(Belt_Array.zip(actors, inboxes), (function (param) {
          var opt = param[1];
          if (opt !== undefined) {
            return [
                    param[0],
                    opt
                  ];
          }
          
        }));
  return await Promise.all(pairs.map(function (param) {
                  var inbox = param[1];
                  console.log("Sending to", inbox);
                  var url = new Nodeurl.URL(inbox);
                  return Egress.post(url.host, url.pathname, {
                              id: Config.actor + "/follow/" + Nodecrypto.randomUUID(),
                              type: "Follow",
                              actor: Config.actor,
                              object: Caml_option.some(param[0])
                            });
                }));
}

Js_promise2.then(main(undefined), (function (res) {
        console.log(res);
        return Promise.resolve(undefined);
      }));

exports.main = main;
/*  Not a pure module */
