// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Fetch = require("./Fetch.js");
let Config = require("./Config.js");
let Egress = require("./Egress.js");
let Nodecrypto = require("node:crypto");
let Stdlib_Array = require("@rescript/runtime/lib/js/Stdlib_Array.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");

async function main() {
  let actors = ["https://dvd.chat/users/9gt1gfwbnibzwcur"];
  let inboxes = await Promise.all(actors.map(Fetch.fetchInbox));
  let pairs = Stdlib_Array.filterMap(Stdlib_Array.zip(actors, inboxes), param => {
    let opt = param[1];
    if (opt !== undefined) {
      return [
        param[0],
        opt
      ];
    }
  });
  return await Promise.all(pairs.map(param => {
    let inbox = param[1];
    console.log("Sending to", inbox);
    return Egress.post(inbox, {
      id: Config.actor + "/follow/" + Nodecrypto.randomUUID(),
      type: "Follow",
      actor: Config.actor,
      object: Primitive_option.some(param[0])
    });
  }));
}

main().then(res => {
  console.log(res);
  return Promise.resolve();
});

exports.main = main;
/*  Not a pure module */
