// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Fetch = require("./Fetch.js");
let Config = require("./Config.js");
let Egress = require("./Egress.js");
let APObject = require("./APObject.js");
let Nodecrypto = require("node:crypto");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");

function actor(e) {
  let match = Stdlib_Option.map(e.headers["accept"], s => s.startsWith("text/html"));
  if (match !== undefined && match) {
    return {
      statusCode: 302,
      headers: Object.fromEntries([[
          "Location",
          Config.baseURL
        ]])
    };
  }
  return {
    statusCode: 200,
    headers: Object.fromEntries([[
        "Content-Type",
        "application/activity+json"
      ]]),
    body: JSON.stringify(Config.actorJSON)
  };
}

async function follow(incoming) {
  let actor = incoming.actor;
  if (actor === undefined) {
    return {
      statusCode: 400,
      body: "Where's your actor?"
    };
  }
  let inbox = await Fetch.fetchInbox(actor);
  if (inbox === undefined) {
    return {
      statusCode: 400,
      body: "Where's your inbox?"
    };
  }
  let res = await Egress.post(inbox, {
    id: Config.actor + "/follow/" + Nodecrypto.randomUUID(),
    type: "Accept",
    actor: Config.actor,
    object: Primitive_option.some(incoming)
  });
  if (res.ok && await Fetch.GitHub.insertToFile(actor, "/followers")) {
    return {
      statusCode: 200
    };
  } else {
    return {
      statusCode: 500,
      body: "Can't post Accept activity or can't update DB"
    };
  }
}

async function unfollow(incoming) {
  let actor = incoming.actor;
  if (actor !== undefined) {
    if (await Fetch.GitHub.removeFromFile(actor, "/followers")) {
      return {
        statusCode: 200
      };
    } else {
      return {
        statusCode: 500,
        body: "Can't update DB"
      };
    }
  } else {
    return {
      statusCode: 400,
      body: "Where's your actor?"
    };
  }
}

let noteBaseLength = (Config.baseURL + "/note").length;

function noteId2Slug(id) {
  return id.slice(noteBaseLength);
}

async function slugExist(slug) {
  try {
    return (await fetch(Config.baseURL + slug, {
      method: "HEAD"
    })).ok;
  } catch (exn) {
    return false;
  }
}

async function nonTextReaction(pathPrefix, undo, incoming) {
  let match = incoming.actor;
  let match$1 = incoming.object;
  if (match === undefined) {
    return {
      statusCode: 400,
      body: "I need both actor and object"
    };
  }
  if (match$1 === undefined) {
    return {
      statusCode: 400,
      body: "I need both actor and object"
    };
  }
  let slug = APObject.getId(Primitive_option.valFromOption(match$1)).slice(noteBaseLength);
  let forMe = await slugExist(slug);
  let path = pathPrefix + slug;
  let update = undo ? Fetch.GitHub.removeFromFile : Fetch.GitHub.insertToFile;
  if (!forMe || await update(match, path)) {
    return {
      statusCode: 200
    };
  } else {
    return {
      statusCode: 500,
      body: "Can't update DB"
    };
  }
}

function like(extra, extra$1) {
  return nonTextReaction("/likes", extra, extra$1);
}

function announce(extra, extra$1) {
  return nonTextReaction("/announces", extra, extra$1);
}

async function create(incoming) {
  let object = incoming.object;
  if (object === undefined) {
    return {
      statusCode: 400,
      body: "I need object"
    };
  }
  let obj = APObject.StringOption.classify(Primitive_option.valFromOption(object));
  if (obj.TAG === "String") {
    return {
      statusCode: 501,
      body: "Give me the whole object, please"
    };
  }
  let obj$1 = obj._0;
  if (obj$1.type !== "Note") {
    return {
      statusCode: 400,
      body: "I only support reply"
    };
  }
  let inReplyTo = obj$1.inReplyTo;
  if (inReplyTo === undefined) {
    return {
      statusCode: 400,
      body: "I only support reply"
    };
  }
  let slug = inReplyTo.slice(noteBaseLength);
  let forMe = await slugExist(slug);
  if (!forMe || await Fetch.GitHub.insertToFile(obj$1, "/all-replies")) {
    return {
      statusCode: 200
    };
  } else {
    return {
      statusCode: 500,
      body: "Can't update DB"
    };
  }
}

async function $$delete(incoming) {
  let object = incoming.object;
  if (object !== undefined) {
    if (await Fetch.GitHub.removeFromFile(Primitive_option.valFromOption(object), "/all-replies")) {
      return {
        statusCode: 200
      };
    } else {
      return {
        statusCode: 500,
        body: "Can't update DB"
      };
    }
  } else {
    return {
      statusCode: 400,
      body: "I need object"
    };
  }
}

async function undo(incoming) {
  let object = incoming.object;
  if (object === undefined) {
    return {
      statusCode: 400,
      body: "I need object"
    };
  }
  let obj = APObject.StringOption.classify(Primitive_option.valFromOption(object));
  if (obj.TAG === "String") {
    return {
      statusCode: 501,
      body: "Give me the whole object, please"
    };
  }
  let obj$1 = obj._0;
  let match = obj$1.type;
  if (match === "Announce") {
    return await nonTextReaction("/announces", true, obj$1);
  } else if (match === "Follow") {
    return await unfollow(obj$1);
  } else if (match === "Like") {
    return await nonTextReaction("/likes", true, obj$1);
  } else {
    return {
      statusCode: 501,
      body: "I can only Undo Follow or Like"
    };
  }
}

exports.actor = actor;
exports.follow = follow;
exports.unfollow = unfollow;
exports.noteBaseLength = noteBaseLength;
exports.noteId2Slug = noteId2Slug;
exports.slugExist = slugExist;
exports.nonTextReaction = nonTextReaction;
exports.like = like;
exports.announce = announce;
exports.create = create;
exports.$$delete = $$delete;
exports.undo = undo;
/* noteBaseLength Not a pure module */
