// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Handle = require("./Handle.js");
let APObject = require("./APObject.js");
let Security = require("./Security.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");

async function handler(event, param) {
  let httpMethod = event.httpMethod;
  let path = event.path;
  console.log({
    httpMethod: httpMethod,
    path: path,
    headers: event.headers
  });
  let post_verified = httpMethod === "POST" && await Security.Signature.verify(event);
  console.log("post_verified:", post_verified);
  let activity = Stdlib_Option.map(event.body, APObject.fromString);
  Stdlib_Option.forEach(activity, x => {
    if (x.TAG === "Ok") {
      console.log("body:", x._0);
      return;
    }
    console.log("Can't parse body as an ActivityStream Object:", x._0);
  });
  let handlers = t => {
    if (t === "Accept" || t === "Note" || t === "OrderedCollection") {
      return param => Promise.resolve({
        statusCode: 400,
        body: "Why are you sending this to me?"
      });
    } else if (t === "Delete") {
      return Handle.$$delete;
    } else if (t === "Follow") {
      return Handle.follow;
    } else if (t === "Create") {
      return Handle.create;
    } else if (t === "Like") {
      return extra => Handle.like(false, extra);
    } else if (t === "Undo") {
      return Handle.undo;
    } else {
      return extra => Handle.announce(false, extra);
    }
  };
  if (httpMethod === "GET") {
    if (path === "/actor") {
      return Handle.actor(event);
    } else {
      return {
        statusCode: 501
      };
    }
  }
  if (httpMethod !== "POST") {
    return {
      statusCode: 501
    };
  }
  if (!post_verified) {
    return {
      statusCode: 401
    };
  }
  if (path !== "/inbox") {
    return {
      statusCode: 501
    };
  }
  if (activity === undefined) {
    return {
      statusCode: 501
    };
  }
  if (activity.TAG !== "Ok") {
    return {
      statusCode: 501
    };
  }
  let act = activity._0;
  return await handlers(act.type)(act);
}

exports.handler = handler;
/* Handle Not a pure module */
