// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


let Buffer = {};

let Crypto = {};

let Fs = {};

let Path = {};

let Process = {};

let URL = {};

exports.Buffer = Buffer;
exports.Crypto = Crypto;
exports.Fs = Fs;
exports.Path = Path;
exports.Process = Process;
exports.URL = URL;
/* No side effect */
