// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


let Global = {};

let Buffer = {};

let Crypto = {};

let Fs = {};

let Path = {};

let Process = {};

let URL = {};

let Http = {};

let Os = {};

let $$Date = {};

exports.Global = Global;
exports.Buffer = Buffer;
exports.Crypto = Crypto;
exports.Fs = Fs;
exports.Path = Path;
exports.Process = Process;
exports.URL = URL;
exports.Http = Http;
exports.Os = Os;
exports.$$Date = $$Date;
/* No side effect */
