// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Fetch = require("./Fetch.js");
let Config = require("./Config.js");
let Nodecrypto = require("node:crypto");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");

function get(text) {
  return Nodecrypto.createHash("sha256").update(text).digest("base64");
}

let Hash = {
  get: get
};

function sign(data) {
  return Nodecrypto.sign("sha256", Buffer.from(data), Config.privateKey).toString("base64");
}

function verify(data, publicKey, signature) {
  return Nodecrypto.verify("sha256", Buffer.from(data), publicKey, Buffer.from(signature, "base64"));
}

function verifyDigest(event) {
  return Stdlib_Option.mapOr(event.headers["digest"], false, x => x === "SHA-256=" + get(Stdlib_Option.getOr(event.body, "")));
}

async function verifySignature(event, keyId, headers, signature) {
  return Stdlib_Option.mapOr(await Fetch.fetchKey(keyId), false, publicKey => {
    let to_be_signed = headers.map(h => {
      let match = event.headers[h];
      if (h === "(request-target)") {
        return `(request-target): ` + event.httpMethod.toLowerCase() + ` ` + event.path;
      } else if (match !== undefined) {
        return h + ": " + match;
      } else {
        return h + ": ";
      }
    }).join("\n");
    return verify(to_be_signed, publicKey, signature);
  });
}

function parse(headers) {
  return Stdlib_Option.map(headers["signature"], s => {
    let dict = Object.fromEntries(s.split(",").map(x => {
      let i = x.indexOf("=");
      return [
        x.slice(0, i),
        x.slice(i + 2 | 0, x.length - 1 | 0)
      ];
    }));
    let keyId = dict["keyId"];
    let signature = dict["signature"];
    let algorithm = dict["algorithm"];
    let headers = Stdlib_Option.map(dict["headers"], s => s.split(" "));
    return [
      keyId,
      signature,
      algorithm,
      headers
    ];
  });
}

async function verify$1(event) {
  let match = parse(event.headers);
  if (match === undefined) {
    return false;
  }
  let keyId = match[0];
  if (keyId === undefined) {
    return false;
  }
  let signature = match[1];
  if (signature === undefined) {
    return false;
  }
  if (match[2] === undefined) {
    return false;
  }
  let headers = match[3];
  if (headers !== undefined && verifyDigest(event)) {
    return await verifySignature(event, keyId, headers, signature);
  } else {
    return false;
  }
}

let Signature = {
  verifyDigest: verifyDigest,
  verifySignature: verifySignature,
  parse: parse,
  verify: verify$1
};

exports.Hash = Hash;
exports.sign = sign;
exports.verify = verify;
exports.Signature = Signature;
/* Fetch Not a pure module */
