// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Fetch = require("./Fetch.js");
let Config = require("./Config.js");
let Egress = require("./Egress.js");
let Nodefs = require("node:fs");
let APObject = require("./APObject.js");
let Nodepath = require("node:path");
let Pervasives = require("@rescript/runtime/lib/js/Pervasives.js");
let Stdlib_Array = require("@rescript/runtime/lib/js/Stdlib_Array.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Stdlib_Result = require("@rescript/runtime/lib/js/Stdlib_Result.js");
let Stdlib_Promise = require("@rescript/runtime/lib/js/Stdlib_Promise.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

async function main() {
  let path_public = Nodepath.join("public", "outbox");
  let path_static = Nodepath.join("static", "outbox");
  let outbox;
  try {
    outbox = Nodefs.readFileSync(path_public, "utf8");
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      outbox = Nodefs.readFileSync(path_static, "utf8");
    } else {
      throw exn;
    }
  }
  let orderedItems = Stdlib_Option.getOr(Stdlib_Result.getOrThrow(APObject.fromString(outbox), undefined).orderedItems, []);
  let obj = APObject.StringOption.classify(orderedItems[0]);
  let last_create_note;
  last_create_note = obj.TAG === "String" ? Pervasives.failwith("I need the Create Object, not Create id") : obj._0;
  console.log("I will send the last note:", APObject.toJSON(last_create_note));
  let path = Nodepath.join("static", "followers");
  let followers = Nodefs.readFileSync(path, "utf8");
  let orderedItems$1 = Stdlib_Option.getOr(Stdlib_Result.getOrThrow(APObject.fromString(followers), undefined).orderedItems, []);
  let followers$1 = orderedItems$1.map(x => {
    let actor = APObject.StringOption.classify(x);
    if (actor.TAG === "String") {
      return actor._0;
    } else {
      return Pervasives.failwith("Followers should be string");
    }
  });
  let inboxes = Stdlib_Array.filterMap(await Promise.all(followers$1.map(actor => Stdlib_Promise.$$catch(Fetch.fetchInbox(actor), e => {
    console.log("Failed to fetch inbox for:", actor);
    console.log("Error:", e);
    return Promise.resolve(undefined);
  }))), x => x).concat(Config.extraInboxes);
  return await Promise.all(inboxes.map(x => {
    console.log("Sending to", x);
    return Egress.post(x, last_create_note);
  }));
}

main().then(res => {
  console.log(res);
  return Promise.resolve();
});

exports.main = main;
/*  Not a pure module */
